ajustes db2

diff --git a/roles/sb2bi_setup_db2/templates/setupdb.sh.j2 b/roles/sb2bi_setup_db2/templates/setupdb.sh.j2
--- a/roles/sb2bi_setup_db2/templates/setupdb.sh.j2
+++ b/roles/sb2bi_setup_db2/templates/setupdb.sh.j2
@@ -1,23 +1,88 @@
 #!/bin/sh
 
+function db2_verify_and_start {
+
+    if ! db2gcf -s | grep Available >/dev/null
+    then
+
+        db2_kill
+        db2_k=$?
+
+        ipclean -a
+
+        db2start
+        db2_start=$?
+        
+        if [[ "$db2_k" -ne  "0" && "$db2_start" -ne  "0" ]]
+        then
+            echo "db2_verify_and_start: ERROR - error detected"
+            exit 1
+        fi
+
+        echo "db2_verify_and_start: sleep "
+        counter=0
+        max_checks=5
+        interval=30
+
+        while [ $counter -lt $max_checks ]; do
+            if db2gcf -s | grep Available >/dev/null; then
+                echo "db2_verify_and_start: DB2 is Avaliable"
+                break  # Exit loop if condition is met
+            else
+                echo "db2_verify_and_start: DB2 is starting. Waiting $interval seconds before next check..."
+                sleep $interval
+                counter=$((counter + 1))
+            fi
+        done
+
+        if [ $counter -eq $max_checks ]; then
+            echo "db2_verify_and_start: ERROR: DB2 is NOT Avaliable. Please check."
+            exit 2
+        fi
+
+    fi
+
+}
+
+
+
+
 function config_settings {
 
-db2set DB2_PARALLEL_IO=ON
-db2set DB2_SKIPDELETED=ON;
-db2set DB2_SKIPINSERTED=ON;
-db2set DB2_USE_ALTERNATE_PAGE_CLEANING=ON;
-db2set DB2_EVALUNCOMMITTED=ON;
-db2set DB2LOCK_TO_RB=STATEMENT;
-db2set DB2COMM=TCPIP;
-# db2 update dbm cfg using DFT_MON_BUFPOOL ON;
-# db2 update dbm cfg using DFT_MON_LOCK ON;
-# db2 update dbm cfg using DFT_MON_SORT ON;
-# db2 update dbm cfg using DFT_MON_STMT ON;
-# db2 update dbm cfg using DFT_MON_TABLE ON;
-# db2 update dbm cfg using DFT_MON_TIMESTAMP ON;
-# db2 update dbm cfg using DFT_MON_UOW ON;
-# db2 update dbm cfg using MON_HEAP_SZ AUTOMATIC;
+    db2set DB2_PARALLEL_IO=ON
+    db2_pi=$?
 
+    db2set DB2_SKIPDELETED=ON;
+    db2_sd=$?
+
+    db2set DB2_SKIPINSERTED=ON;
+    db2_si=$?
+
+    db2set DB2_USE_ALTERNATE_PAGE_CLEANING=ON;
+    db2_uapc=$?
+
+    db2set DB2_EVALUNCOMMITTED=ON;
+    db2_eu=$?
+
+    db2set DB2LOCK_TO_RB=STATEMENT;
+    db2_lock=$?
+
+    db2set DB2COMM=TCPIP;
+    db2_comm=$?
+    # db2 update dbm cfg using DFT_MON_BUFPOOL ON;
+    # db2 update dbm cfg using DFT_MON_LOCK ON;
+    # db2 update dbm cfg using DFT_MON_SORT ON;
+    # db2 update dbm cfg using DFT_MON_STMT ON;
+    # db2 update dbm cfg using DFT_MON_TABLE ON;
+    # db2 update dbm cfg using DFT_MON_TIMESTAMP ON;
+    # db2 update dbm cfg using DFT_MON_UOW ON;
+    # db2 update dbm cfg using MON_HEAP_SZ AUTOMATIC;
+
+    if [[ "$db2_pi" -ne  "0" && "$db2_sd" -ne  "0" && "$db2_si" -ne "0"  && "$db2_uapc" -ne "0" && "$db2_eu" -ne "0" && "$db2_lock" -ne "0" &&  "$db2_comm" -ne "0" ]]
+    then
+        echo "config_settings: ERROR - error detected"
+        exit 1
+    fi
 }
 
 function create_b2bi_db {
@@ -69,17 +134,17 @@ CONNECT RESET;
 EOF
 
     if [[ ! -f "/tmp/create_b2bi_db2.sql" ]]; then
-        echo "ERROR: Cannot generate create_b2bi_db2.sql"
+        echo "create_b2bi_db: ERROR - Cannot generate create_b2bi_db2.sql"
         exit 1
     fi
     
     echo "create_b2bi_db: File /tmp/create_b2bi_db2.sql created sucessfully"
 
     db2 -tvf /tmp/create_b2bi_db2.sql -z /tmp/create_b2bi_db2.sql.log 
+    db2_crdb=$?
 
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        echo "ERROR: Failed to run 'db2 -tvf create_b2bi_db2.sql'"
+    if [ $db2_crdb -ne 0 ]; then
+        echo "create_b2bi_db: ERROR - Failed to run 'db2 -tvf create_b2bi_db2.sql'"
         exit 2
     fi
 
@@ -89,32 +154,55 @@ EOF
 function apply_settings {
 
     db2 connect to {{ db2_dbname }}
+    db2_ct=$?
 
     rc=$?
     if [ $rc -ne 0 ]; then
-        echo "ERROR: Failed to connect to db2"
+        echo "apply_settings: ERROR - Failed to connect to db2"
         exit 1
     fi
 
+
     echo "apply_settings: connected to {{ db2_dbname }} sucessfully"
 
-    # db2 update db cfg for {{ db2_dbname }} using CATALOGCACHE_SZ 300;
-    # db2 update db cfg for {{ db2_dbname }} using UTIL_HEAP_SZ AUTOMATIC;
-    # db2 update db cfg for {{ db2_dbname }} using CHNGPGS_THRESH 80;
+    db2 update db cfg for {{ db2_dbname }} using CATALOGCACHE_SZ 300;
+    db2_updb_1=$?
+
+    db2 update db cfg for {{ db2_dbname }} using UTIL_HEAP_SZ AUTOMATIC;
+    db2_updb_2=$?
+
+    db2 update db cfg for {{ db2_dbname }} using CHNGPGS_THRESH 80;
+    db2_updb_3=$?
+
+    if [ "$db2_updb_1" -ne  "0" && "$db2_updb_2" -ne  "0" && "$db2_updb_3" -ne  "0" ]; then
+        echo "apply_settings: ERROR - Failed to start to db2"
+        exit 3
+    fi
+
 
     db2 connect reset
+    db2_cr=$?
+
     db2 terminate
+    db2_t=$?
+
     db2 force applications all
+    db2_fal=$?
+
     db2 deactivate db {{ db2_dbname }}
+    db2_ddb=$?
+
     echo "Run db2stop"
     db2stop
+    db2_stop=$?
+
     echo "Run db2start"
     db2start
+    db2_start=$?
 
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        echo "ERROR: Failed to start to db2"
-        exit 2
+    if [ "$db2_cr" -ne  "0" && "$db2_t" -ne  "0" && "$db2_fal" -ne  "0" && "$db2_ddb" -ne  "0" && "$db2_stop" -ne  "0" && "$db2_start" -ne  "0" ]; then
+        echo "apply_settings: ERROR - Failed to start to db2"
+        exit 3
     fi
     echo "apply_settings: finished sucessfully"
 }
@@ -122,13 +210,16 @@ function apply_settings {
 ########################## Main Part of Shell Script ##########################
 echo "Start of script setupdb.sh"
 echo "Starting db2"
-db2start
+db2_verify_and_start
+
 
 echo "Creating Sterling B2Bi Database"
 create_b2bi_db
 
+
 echo "Define Config settings to DB2"
 config_settings
+
 
 echo "Applying settings to DB2"
 apply_settings
